/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitoring/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monitoring Overview */
        get: operations["monitoring_overview_api_v1_monitoring_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitoring/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monitoring Runs */
        get: operations["monitoring_runs_api_v1_monitoring_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Run */
        post: operations["execute_run_api_v1_runs__run_id__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Explain */
        get: operations["run_explain_api_v1_runs__run_id__explain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/reaction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Run Reaction */
        post: operations["add_run_reaction_api_v1_runs__run_id__reaction_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Result */
        get: operations["run_result_api_v1_runs__run_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Status */
        get: operations["run_status_api_v1_runs__run_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_api_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/intent-consult": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Intent Consultation */
        get: operations["get_intent_consultation_api_v1_sessions__session_id__intent_consult_get"];
        put?: never;
        /** Consult Intent */
        post: operations["consult_intent_api_v1_sessions__session_id__intent_consult_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/match-brief": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build Match Brief */
        post: operations["build_match_brief_api_v1_sessions__session_id__match_brief_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Resume */
        post: operations["upload_resume_api_v1_sessions__session_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/resume-confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Confirm */
        post: operations["resume_confirm_api_v1_sessions__session_id__resume_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/resume-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resume Preview */
        get: operations["resume_preview_api_v1_sessions__session_id__resume_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_resume_api_v1_sessions__session_id__resume_post */
        Body_upload_resume_api_v1_sessions__session_id__resume_post: {
            /** File */
            file: string;
        };
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            /**
             * Api Version
             * @default v1
             * @constant
             */
            api_version: "v1";
            /** Dual Space Enabled */
            dual_space_enabled: boolean;
            /**
             * Execution Durability
             * @default process_local
             * @constant
             */
            execution_durability: "process_local";
            /** Explain Enabled */
            explain_enabled: boolean;
            /** Monitoring Enabled */
            monitoring_enabled: boolean;
        };
        /** CareerDirectionResponse */
        CareerDirectionResponse: {
            /**
             * Entry Role
             * @default
             */
            entry_role: string;
            /**
             * Primary Gap
             * @default
             */
            primary_gap: string;
            /** Rationale */
            rationale: string;
            /** Resume Evidence Span Ids */
            resume_evidence_span_ids?: string[];
            /** Role Family */
            role_family: string;
            /** Title */
            title: string;
        };
        /** CareerPathItem */
        CareerPathItem: {
            /** Action */
            action: string;
            /** Evidence Span Ids */
            evidence_span_ids?: string[];
            /**
             * Horizon
             * @enum {string}
             */
            horizon: "short" | "medium" | "long";
        };
        /** CaseEvidenceResponse */
        CaseEvidenceResponse: {
            /** Case Id */
            case_id: string;
            /** Confidence */
            confidence?: number | null;
            /** Highest Stage */
            highest_stage: string;
        };
        /** EvidenceItem */
        EvidenceItem: {
            /** Content */
            content: string;
            /** Evidence Span Id */
            evidence_span_id: string;
            /** Field */
            field?: string | null;
        };
        /** ExecuteRunRequest */
        ExecuteRunRequest: {
            /** Plan Hash */
            plan_hash: string;
            /** Plan Version */
            plan_version: number;
        };
        /** FusionResponse */
        FusionResponse: {
            /** Implicit Max Weight */
            implicit_max_weight: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IntentConsultRequest */
        IntentConsultRequest: {
            /** Clarification Answer */
            clarification_answer?: string | null;
            /**
             * Company Exclusive
             * @default false
             */
            company_exclusive: boolean;
            /** Goal Text */
            goal_text?: string | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "targeted" | "explore";
            /** Target Companies */
            target_companies?: string[];
            /** Target Roles */
            target_roles?: string[];
        };
        /** IntentConsultResponse */
        IntentConsultResponse: {
            /** Assistant Message */
            assistant_message: string;
            /** Avoid Roles */
            avoid_roles?: string[];
            /** Clarification Question */
            clarification_question?: string | null;
            /**
             * Clarification Used
             * @default 0
             */
            clarification_used: number;
            /** Current Goal */
            current_goal?: string[];
            /** Directions */
            directions?: components["schemas"]["CareerDirectionResponse"][];
            /** Hard Constraints */
            hard_constraints?: {
                [key: string]: unknown;
            };
            /** Long Term Goal */
            long_term_goal?: string[];
            /**
             * Mode
             * @enum {string}
             */
            mode: "targeted" | "explore";
            /**
             * Needs Clarification
             * @default false
             */
            needs_clarification: boolean;
            /** Session Id */
            session_id: string;
            /** Soft Preferences */
            soft_preferences?: {
                [key: string]: unknown;
            };
        };
        /** MatchBrief */
        MatchBrief: {
            /** Avoid Roles */
            avoid_roles?: string[];
            /** Career Goal */
            career_goal: string;
            /** Clarification Question */
            clarification_question?: string | null;
            /** Conflicts */
            conflicts?: string[];
            /** Hard Constraints */
            hard_constraints?: {
                [key: string]: unknown;
            };
            /**
             * Needs Clarification
             * @default false
             */
            needs_clarification: boolean;
            /** Plan Hash */
            plan_hash: string;
            /** Plan Version */
            plan_version: number;
            /**
             * Result Count
             * @default 5
             */
            result_count: number;
            /** Soft Preferences */
            soft_preferences?: {
                [key: string]: unknown;
            };
        };
        /** MatchBriefRequest */
        MatchBriefRequest: {
            /** Avoid Roles */
            avoid_roles?: string[];
            /** Career Goal */
            career_goal: string;
            /** Clarification Question */
            clarification_question?: string | null;
            /** Conflicts */
            conflicts?: string[];
            /** Hard Constraints */
            hard_constraints?: {
                [key: string]: unknown;
            };
            /**
             * Needs Clarification
             * @default false
             */
            needs_clarification: boolean;
            /**
             * Result Count
             * @default 5
             */
            result_count: number;
            /** Soft Preferences */
            soft_preferences?: {
                [key: string]: unknown;
            };
        };
        /** MatchBriefResponse */
        MatchBriefResponse: {
            brief: components["schemas"]["MatchBrief"];
            /** Run Id */
            run_id: string;
            /** Session Id */
            session_id: string;
        };
        /** MonitoringOverviewResponse */
        MonitoringOverviewResponse: {
            /** Average Recommendation Count */
            average_recommendation_count: number;
            /** Completion Rate */
            completion_rate: number;
            /** Duration P50 Ms */
            duration_p50_ms?: number | null;
            /** Duration P95 Ms */
            duration_p95_ms?: number | null;
            /** Failure Rate */
            failure_rate: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Implicit Usage Rate */
            implicit_usage_rate: number;
            /** Jd Evidence Coverage Rate */
            jd_evidence_coverage_rate: number;
            /** Reordered Run Count */
            reordered_run_count: number;
            /** Stage Latencies */
            stage_latencies?: components["schemas"]["StageLatencyResponse"][];
            /** Status Counts */
            status_counts?: {
                [key: string]: number;
            };
            /** Total Runs */
            total_runs: number;
            /** Warning Rate */
            warning_rate: number;
            /** Window Hours */
            window_hours: number;
        };
        /** ProductResult */
        ProductResult: {
            /** Career Path */
            career_path?: components["schemas"]["CareerPathItem"][];
            /** Recommended Roles */
            recommended_roles?: components["schemas"]["RecommendationResult"][];
            /** Resume Strategy */
            resume_strategy?: components["schemas"]["ResumeAdvice"][];
            /** Skill Gaps */
            skill_gaps?: components["schemas"]["SkillGap"][];
            /** Summary */
            summary: string;
            /** Warnings */
            warnings?: string[];
        };
        /** RankTraceResponse */
        RankTraceResponse: {
            /** Case Evidence */
            case_evidence?: components["schemas"]["CaseEvidenceResponse"][];
            /** Case Ids */
            case_ids?: string[];
            /** Explicit Rank */
            explicit_rank?: number | null;
            /** Explicit Score */
            explicit_score?: number | null;
            /** Final Rank */
            final_rank: number;
            /** Implicit Confidence */
            implicit_confidence?: number | null;
            /** Implicit Rank */
            implicit_rank?: number | null;
            /** Implicit Score */
            implicit_score?: number | null;
            /** Implicit Weight */
            implicit_weight: number;
            /** Job Id */
            job_id: string;
        };
        /** ReactionRequest */
        ReactionRequest: {
            /** Idempotency Key */
            idempotency_key?: string | null;
            /** Job Id */
            job_id: string;
            /** Outcome */
            outcome: string;
            /** Reason */
            reason?: string | null;
            /** User Rating */
            user_rating?: number | null;
        };
        /** ReactionResponse */
        ReactionResponse: {
            /** Feedback Id */
            feedback_id: number;
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @default reaction_recorded
             * @constant
             */
            status: "reaction_recorded";
        };
        /** RecentRunResponse */
        RecentRunResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Error Code */
            error_code?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Recommendation Count
             * @default 0
             */
            recommendation_count: number;
            /** Run Id */
            run_id: string;
            /** Stage */
            stage?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Warning Codes */
            warning_codes?: string[];
        };
        /** RecentRunsResponse */
        RecentRunsResponse: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Runs */
            runs?: components["schemas"]["RecentRunResponse"][];
            /** Window Hours */
            window_hours: number;
        };
        /** RecommendationResult */
        RecommendationResult: {
            /** Company */
            company?: string | null;
            /** Concise Explanation */
            concise_explanation: string;
            /** Evidence */
            evidence?: components["schemas"]["EvidenceItem"][];
            /** Job Id */
            job_id: string;
            /**
             * Listing Kind
             * @default dataset_only
             * @enum {string}
             */
            listing_kind: "source_url" | "dataset_only";
            /** Location */
            location?: string | null;
            /** Resume Evidence */
            resume_evidence?: components["schemas"]["EvidenceItem"][];
            /** Source Url */
            source_url?: string | null;
            /**
             * Tier
             * @enum {string}
             */
            tier: "now_fit" | "stretch_fit" | "bridge_role";
            /** Title */
            title?: string | null;
            /** Why This Match */
            why_this_match?: string[];
        };
        /** RecoveryEventResponse */
        RecoveryEventResponse: {
            /** Attempt */
            attempt: number;
            /** Max Attempts */
            max_attempts: number;
            /** Reason */
            reason: string;
            /** Stage */
            stage: string;
        };
        /** ResumeAcceptedResponse */
        ResumeAcceptedResponse: {
            /** Session Id */
            session_id: string;
            /**
             * Status
             * @default resume_queued
             * @constant
             */
            status: "resume_queued";
        };
        /** ResumeAdvice */
        ResumeAdvice: {
            /** Evidence Span Ids */
            evidence_span_ids?: string[];
            /** Section */
            section: string;
            /** Suggestion */
            suggestion: string;
        };
        /** ResumeConfirmResponse */
        ResumeConfirmResponse: {
            /** Confirmed */
            confirmed: boolean;
            /** Confirmed At */
            confirmed_at?: string | null;
            /** Resume Version */
            resume_version: number;
            /** Session Id */
            session_id: string;
        };
        /** ResumeEducationPreview */
        ResumeEducationPreview: {
            /**
             * Dates
             * @default
             */
            dates: string;
            /**
             * Degree
             * @default
             */
            degree: string;
            /** Details */
            details?: string[];
            /** Evidence Span Ids */
            evidence_span_ids?: string[];
            /**
             * Field
             * @default
             */
            field: string;
            /**
             * Institution
             * @default
             */
            institution: string;
        };
        /** ResumeEvidencePreview */
        ResumeEvidencePreview: {
            /** Content */
            content: string;
            /** Evidence Span Id */
            evidence_span_id: string;
        };
        /** ResumeExperiencePreview */
        ResumeExperiencePreview: {
            /** Achievements */
            achievements?: string[];
            /**
             * Dates
             * @default
             */
            dates: string;
            /** Evidence Span Ids */
            evidence_span_ids?: string[];
            /**
             * Location
             * @default
             */
            location: string;
            /**
             * Organization
             * @default
             */
            organization: string;
            /** Responsibilities */
            responsibilities?: string[];
            /** Technologies */
            technologies?: string[];
            /**
             * Title
             * @default
             */
            title: string;
        };
        /** ResumePreviewResponse */
        ResumePreviewResponse: {
            /** Confirmed */
            confirmed: boolean;
            /** Education */
            education?: components["schemas"]["ResumeEducationPreview"][];
            /** Evidence */
            evidence?: components["schemas"]["ResumeEvidencePreview"][];
            /** Experience */
            experience?: components["schemas"]["ResumeExperiencePreview"][];
            /** Projects */
            projects?: components["schemas"]["ResumeProjectPreview"][];
            /** Resume Quality Issues */
            resume_quality_issues?: string[];
            /** Resume Version */
            resume_version: number;
            /** Session Id */
            session_id: string;
            /** Skills */
            skills?: string[];
        };
        /** ResumeProjectPreview */
        ResumeProjectPreview: {
            /** Actions */
            actions?: string[];
            /**
             * Dates
             * @default
             */
            dates: string;
            /** Evidence Span Ids */
            evidence_span_ids?: string[];
            /**
             * Name
             * @default
             */
            name: string;
            /** Outcomes */
            outcomes?: string[];
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Technologies */
            technologies?: string[];
        };
        /** RunExplainResponse */
        RunExplainResponse: {
            fusion: components["schemas"]["FusionResponse"];
            /** Rank Trace */
            rank_trace?: components["schemas"]["RankTraceResponse"][];
            /** Recovery Events */
            recovery_events?: components["schemas"]["RecoveryEventResponse"][];
            /** Run Id */
            run_id: string;
            /** Stage Durations Ms */
            stage_durations_ms?: {
                [key: string]: number;
            };
        };
        /** RunResultResponse */
        RunResultResponse: {
            result: components["schemas"]["ProductResult"];
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
        };
        /** RunStatusResponse */
        RunStatusResponse: {
            /** Completed Stages */
            completed_stages?: string[];
            /** Error Code */
            error_code?: string | null;
            /** Execution Durability */
            execution_durability: string;
            /** Plan Hash */
            plan_hash?: string | null;
            /** Plan Version */
            plan_version: number;
            /** Result Ready */
            result_ready: boolean;
            /** Retry After Ms */
            retry_after_ms?: number | null;
            /** Run Id */
            run_id: string;
            /** Session Id */
            session_id: string;
            /** Stage */
            stage?: string | null;
            /** Status */
            status: string;
            /**
             * Total Stages
             * @default 7
             */
            total_stages: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Warning Codes */
            warning_codes?: string[];
        };
        /** SessionCreateRequest */
        SessionCreateRequest: {
            /** User Id */
            user_id: string;
        };
        /** SessionResponse */
        SessionResponse: {
            /** Session Id */
            session_id: string;
            /** Status */
            status: string;
        };
        /** SkillGap */
        SkillGap: {
            /** Evidence Span Ids */
            evidence_span_ids?: string[];
            /**
             * Gap
             * @default
             */
            gap: string;
            /**
             * Priority
             * @default
             * @enum {string}
             */
            priority: "low" | "medium" | "high" | "";
            /** Skill */
            skill: string;
        };
        /** StageLatencyResponse */
        StageLatencyResponse: {
            /** P50 Ms */
            p50_ms?: number | null;
            /** P95 Ms */
            p95_ms?: number | null;
            /** Stage */
            stage: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    capabilities_api_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    monitoring_overview_api_v1_monitoring_overview_get: {
        parameters: {
            query?: {
                window_hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitoringOverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    monitoring_runs_api_v1_monitoring_runs_get: {
        parameters: {
            query?: {
                window_hours?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecentRunsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_run_api_v1_runs__run_id__execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecuteRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_explain_api_v1_runs__run_id__explain_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunExplainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_run_reaction_api_v1_runs__run_id__reaction_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReactionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_result_api_v1_runs__run_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_status_api_v1_runs__run_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_intent_consultation_api_v1_sessions__session_id__intent_consult_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentConsultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consult_intent_api_v1_sessions__session_id__intent_consult_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntentConsultRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentConsultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_match_brief_api_v1_sessions__session_id__match_brief_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchBriefRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchBriefResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_resume_api_v1_sessions__session_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_resume_api_v1_sessions__session_id__resume_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeAcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_confirm_api_v1_sessions__session_id__resume_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeConfirmResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_preview_api_v1_sessions__session_id__resume_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumePreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
