/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Otp */
        post: operations["request_otp_api_v1_auth_otp_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Login Otp */
        post: operations["verify_login_otp_api_v1_auth_otp_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_v1_me_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Profile */
        patch: operations["patch_profile_api_v1_me_profile_patch"];
        trace?: never;
    };
    "/api/v1/me/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Sessions */
        get: operations["get_my_sessions_api_v1_me_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_api_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Resume
         * @description B2 上传确认流：存库 + 本地提取（零 LLM），等待用户「确认解析」。
         */
        post: operations["upload_resume_api_v1_sessions__session_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/resume-upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pending Resume Upload
         * @description 刷新恢复：仅 resume_uploaded 态返回待解析上传元数据，否则 404。
         */
        get: operations["pending_resume_upload_api_v1_sessions__session_id__resume_upload_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/resume/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse Resume
         * @description 确认解析（LLM 成本发生点）：CAS 扣一次解析额度并入队后台归一化。
         */
        post: operations["parse_resume_api_v1_sessions__session_id__resume_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/resume-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resume Preview */
        get: operations["resume_preview_api_v1_sessions__session_id__resume_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/resume-confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Confirm */
        post: operations["resume_confirm_api_v1_sessions__session_id__resume_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/consult": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Consultation */
        get: operations["get_consultation_api_v1_sessions__session_id__consult_get"];
        put?: never;
        /** Continue Consultation */
        post: operations["continue_consultation_api_v1_sessions__session_id__consult_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/consult/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize Consultation */
        post: operations["finalize_consultation_api_v1_sessions__session_id__consult_finalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/match-brief": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build Match Brief */
        post: operations["build_match_brief_api_v1_sessions__session_id__match_brief_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Run */
        post: operations["execute_run_api_v1_runs__run_id__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Status */
        get: operations["run_status_api_v1_runs__run_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/conversation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Conversation */
        get: operations["run_conversation_api_v1_runs__run_id__conversation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Result */
        get: operations["run_result_api_v1_runs__run_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Explain */
        get: operations["run_explain_api_v1_runs__run_id__explain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/reaction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Run Reaction */
        post: operations["add_run_reaction_api_v1_runs__run_id__reaction_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitoring/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monitoring Overview */
        get: operations["monitoring_overview_api_v1_monitoring_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitoring/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monitoring Runs */
        get: operations["monitoring_runs_api_v1_monitoring_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_resume_api_v1_sessions__session_id__resume_post */
        Body_upload_resume_api_v1_sessions__session_id__resume_post: {
            /** File */
            file: string;
        };
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            /**
             * Api Version
             * @default v1
             * @constant
             */
            api_version: "v1";
            /** Dual Space Enabled */
            dual_space_enabled: boolean;
            /** Explain Enabled */
            explain_enabled: boolean;
            /** Monitoring Enabled */
            monitoring_enabled: boolean;
            /**
             * Execution Durability
             * @default process_local
             * @constant
             */
            execution_durability: "process_local";
            /** Otp Channels */
            otp_channels?: ("email" | "phone")[];
        };
        /** CareerPathItem */
        CareerPathItem: {
            /**
             * Horizon
             * @enum {string}
             */
            horizon: "short" | "medium" | "long";
            /** Action */
            action: string;
            /** Evidence Span Ids */
            evidence_span_ids?: string[];
        };
        /** CaseEvidenceResponse */
        CaseEvidenceResponse: {
            /** Case Id */
            case_id: string;
            /** Highest Stage */
            highest_stage: string;
            /** Confidence */
            confidence?: number | null;
        };
        /** ClarificationProgress */
        ClarificationProgress: {
            /**
             * Answered
             * @default 0
             */
            answered: number;
            /**
             * Skipped
             * @default 0
             */
            skipped: number;
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Questions Used
             * @default 0
             */
            questions_used: number;
        };
        /** ConsultBriefDraftResponse */
        ConsultBriefDraftResponse: {
            /** Career Goal */
            career_goal: string;
            /** Hard Constraints */
            hard_constraints?: {
                [key: string]: unknown;
            };
            /** Soft Preferences */
            soft_preferences?: {
                [key: string]: unknown;
            };
            /** Avoid Roles */
            avoid_roles?: string[];
            /**
             * Result Count
             * @default 5
             */
            result_count: number;
        };
        /** ConsultProfileDraft */
        ConsultProfileDraft: {
            /** Current Goal */
            current_goal?: string[];
            /** Long Term Goal */
            long_term_goal?: string[];
            /** Hard Constraints */
            hard_constraints?: {
                [key: string]: unknown;
            };
            /** Soft Preferences */
            soft_preferences?: {
                [key: string]: unknown;
            };
            /** Avoid Roles */
            avoid_roles?: string[];
        };
        /** ConsultRequest */
        ConsultRequest: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "targeted" | "explore";
            /** Message */
            message: string;
            /** Expected Round */
            expected_round: number;
        };
        /** ConsultResponse */
        ConsultResponse: {
            /** Assistant Reply */
            assistant_reply: string;
            /** Next Question */
            next_question: string;
            /**
             * Phase
             * @enum {string}
             */
            phase: "template" | "resume_clarify" | "deepen" | "explore";
            /** Completeness */
            completeness: number;
            /** Can Finalize */
            can_finalize: boolean;
            /** Round */
            round: number;
            profile_draft: components["schemas"]["ConsultProfileDraft"];
            clarification_progress?: components["schemas"]["ClarificationProgress"];
        };
        /** ConsultStateResponse */
        ConsultStateResponse: {
            /** Transcript */
            transcript?: components["schemas"]["ConsultTranscriptEntry"][];
            profile_draft: components["schemas"]["ConsultProfileDraft"];
            /** Round */
            round: number;
            /**
             * Phase
             * @enum {string}
             */
            phase: "template" | "resume_clarify" | "deepen" | "explore";
            /** Completeness */
            completeness: number;
            /** Can Finalize */
            can_finalize: boolean;
            clarification_progress?: components["schemas"]["ClarificationProgress"];
        };
        /** ConsultTranscriptEntry */
        ConsultTranscriptEntry: {
            /** Round */
            round: number;
            /** User Message */
            user_message: string;
            /** Assistant Reply */
            assistant_reply: string;
            /** Next Question */
            next_question: string;
            /**
             * Phase
             * @enum {string}
             */
            phase: "template" | "resume_clarify" | "deepen" | "explore";
            /** Supervisor Notes */
            supervisor_notes?: components["schemas"]["SupervisorNote"][];
        };
        /** ConversationMessageResponse */
        ConversationMessageResponse: {
            /** Seq */
            seq: number;
            /**
             * Persona
             * @enum {string}
             */
            persona: "intent_consultant" | "job_scout" | "strategist" | "pm";
            /** Display Name */
            display_name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "intro" | "brief" | "progress" | "checkpoint" | "recovery" | "result" | "warning" | "error";
            /** Text */
            text: string;
            /** Stage */
            stage: string;
        };
        /** EvidenceItem */
        EvidenceItem: {
            /** Evidence Span Id */
            evidence_span_id: string;
            /** Field */
            field?: string | null;
            /** Content */
            content: string;
        };
        /** ExecuteRunRequest */
        ExecuteRunRequest: {
            /** Plan Version */
            plan_version: number;
            /** Plan Hash */
            plan_hash: string;
        };
        /** FusionResponse */
        FusionResponse: {
            /** Implicit Max Weight */
            implicit_max_weight: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MatchBrief */
        MatchBrief: {
            /** Career Goal */
            career_goal: string;
            /** Hard Constraints */
            hard_constraints?: {
                [key: string]: unknown;
            };
            /** Soft Preferences */
            soft_preferences?: {
                [key: string]: unknown;
            };
            /** Avoid Roles */
            avoid_roles?: string[];
            /**
             * Result Count
             * @default 5
             */
            result_count: number;
            /** Conflicts */
            conflicts?: string[];
            /**
             * Needs Clarification
             * @default false
             */
            needs_clarification: boolean;
            /** Clarification Question */
            clarification_question?: string | null;
            /** Plan Version */
            plan_version: number;
            /** Plan Hash */
            plan_hash: string;
        };
        /** MatchBriefRequest */
        MatchBriefRequest: {
            /** Career Goal */
            career_goal: string;
            /** Hard Constraints */
            hard_constraints?: {
                [key: string]: unknown;
            };
            /** Soft Preferences */
            soft_preferences?: {
                [key: string]: unknown;
            };
            /** Avoid Roles */
            avoid_roles?: string[];
            /**
             * Result Count
             * @default 5
             */
            result_count: number;
            /** Conflicts */
            conflicts?: string[];
            /**
             * Needs Clarification
             * @default false
             */
            needs_clarification: boolean;
            /** Clarification Question */
            clarification_question?: string | null;
        };
        /** MatchBriefResponse */
        MatchBriefResponse: {
            /** Run Id */
            run_id: string;
            /** Session Id */
            session_id: string;
            brief: components["schemas"]["MatchBrief"];
        };
        /** MeResponse */
        MeResponse: {
            /** User Id */
            user_id: string;
            /** Display Name */
            display_name?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
            /** Status */
            status: string;
            /** Is Admin */
            is_admin: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Login At */
            last_login_at?: string | null;
        };
        /** MeSessionResponse */
        MeSessionResponse: {
            /** Session Id */
            session_id: string;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MeSessionsResponse */
        MeSessionsResponse: {
            /** Sessions */
            sessions?: components["schemas"]["MeSessionResponse"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Has More */
            has_more: boolean;
        };
        /** MonitoringOverviewResponse */
        MonitoringOverviewResponse: {
            /** Window Hours */
            window_hours: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Total Runs */
            total_runs: number;
            /** Status Counts */
            status_counts?: {
                [key: string]: number;
            };
            /** Completion Rate */
            completion_rate: number;
            /** Warning Rate */
            warning_rate: number;
            /** Failure Rate */
            failure_rate: number;
            /** Duration P50 Ms */
            duration_p50_ms?: number | null;
            /** Duration P95 Ms */
            duration_p95_ms?: number | null;
            /** Stage Latencies */
            stage_latencies?: components["schemas"]["StageLatencyResponse"][];
            /** Average Recommendation Count */
            average_recommendation_count: number;
            /** Jd Evidence Coverage Rate */
            jd_evidence_coverage_rate: number;
            /** Implicit Usage Rate */
            implicit_usage_rate: number;
            /** Reordered Run Count */
            reordered_run_count: number;
        };
        /** OtpRequest */
        OtpRequest: {
            /**
             * Channel
             * @enum {string}
             */
            channel: "email" | "phone";
            /** Target */
            target: string;
        };
        /** OtpRequestAccepted */
        OtpRequestAccepted: {
            /**
             * Status
             * @default otp_accepted
             * @constant
             */
            status: "otp_accepted";
        };
        /** OtpVerifyRequest */
        OtpVerifyRequest: {
            /**
             * Channel
             * @enum {string}
             */
            channel: "email" | "phone";
            /** Target */
            target: string;
            /** Code */
            code: string;
        };
        /** ProductResult */
        ProductResult: {
            /** Summary */
            summary: string;
            /** Recommended Roles */
            recommended_roles?: components["schemas"]["RecommendationResult"][];
            /** Resume Strategy */
            resume_strategy?: components["schemas"]["ResumeAdvice"][];
            /** Skill Gaps */
            skill_gaps?: components["schemas"]["SkillGap"][];
            /** Career Path */
            career_path?: components["schemas"]["CareerPathItem"][];
            /** Warnings */
            warnings?: string[];
        };
        /** ProfilePatchRequest */
        ProfilePatchRequest: {
            /** Profile */
            profile: {
                [key: string]: unknown;
            };
        };
        /** ProfileResponse */
        ProfileResponse: {
            /** Profile */
            profile?: {
                [key: string]: unknown;
            };
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RankTraceResponse */
        RankTraceResponse: {
            /** Job Id */
            job_id: string;
            /** Final Rank */
            final_rank: number;
            /** Explicit Rank */
            explicit_rank?: number | null;
            /** Implicit Rank */
            implicit_rank?: number | null;
            /** Explicit Score */
            explicit_score?: number | null;
            /** Implicit Score */
            implicit_score?: number | null;
            /** Implicit Confidence */
            implicit_confidence?: number | null;
            /** Implicit Weight */
            implicit_weight: number;
            /** Case Ids */
            case_ids?: string[];
            /** Case Evidence */
            case_evidence?: components["schemas"]["CaseEvidenceResponse"][];
        };
        /** ReactionRequest */
        ReactionRequest: {
            /** Job Id */
            job_id: string;
            /** Outcome */
            outcome: string;
            /** Reason */
            reason?: string | null;
            /** User Rating */
            user_rating?: number | null;
            /** Idempotency Key */
            idempotency_key?: string | null;
        };
        /** ReactionResponse */
        ReactionResponse: {
            /** Run Id */
            run_id: string;
            /** Feedback Id */
            feedback_id: number;
            /**
             * Status
             * @default reaction_recorded
             * @constant
             */
            status: "reaction_recorded";
        };
        /** RecentRunResponse */
        RecentRunResponse: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
            /** Stage */
            stage?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /**
             * Recommendation Count
             * @default 0
             */
            recommendation_count: number;
            /** Warning Codes */
            warning_codes?: string[];
            /** Error Code */
            error_code?: string | null;
        };
        /** RecentRunsResponse */
        RecentRunsResponse: {
            /** Window Hours */
            window_hours: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Runs */
            runs?: components["schemas"]["RecentRunResponse"][];
        };
        /** RecommendationResult */
        RecommendationResult: {
            /** Job Id */
            job_id: string;
            /** Title */
            title?: string | null;
            /** Company */
            company?: string | null;
            /** Location */
            location?: string | null;
            /**
             * Tier
             * @enum {string}
             */
            tier: "now_fit" | "stretch_fit" | "bridge_role";
            /** Concise Explanation */
            concise_explanation: string;
            /** Why This Match */
            why_this_match?: string[];
            /** Evidence */
            evidence?: components["schemas"]["EvidenceItem"][];
            /** Resume Evidence */
            resume_evidence?: components["schemas"]["EvidenceItem"][];
            /** Source Url */
            source_url?: string | null;
            /**
             * Listing Kind
             * @default dataset_only
             * @enum {string}
             */
            listing_kind: "source_url" | "dataset_only";
            /** Demo Synthetic */
            demo_synthetic?: boolean | null;
            /** Country Code */
            country_code?: ("CN" | "UK") | null;
        };
        /** RecoveryEventResponse */
        RecoveryEventResponse: {
            /** Stage */
            stage: string;
            /** Reason */
            reason: string;
            /** Attempt */
            attempt: number;
            /** Max Attempts */
            max_attempts: number;
        };
        /**
         * RequestValidationErrorResponse
         * @description 默认 422 数组形态——与自定义必填 detail 组成 anyOf，保证契约加性。
         */
        RequestValidationErrorResponse: {
            /** Detail */
            detail?: components["schemas"]["ValidationErrorItem"][];
        } & {
            [key: string]: unknown;
        };
        /** ResumeAcceptedResponse */
        ResumeAcceptedResponse: {
            /** Session Id */
            session_id: string;
            /**
             * Status
             * @default resume_queued
             * @constant
             */
            status: "resume_queued";
        };
        /** ResumeAdvice */
        ResumeAdvice: {
            /** Section */
            section: string;
            /** Suggestion */
            suggestion: string;
            /** Evidence Span Ids */
            evidence_span_ids?: string[];
        };
        /** ResumeConfirmRequest */
        ResumeConfirmRequest: {
            /** Expected Resume Version */
            expected_resume_version?: number | null;
        };
        /** ResumeConfirmResponse */
        ResumeConfirmResponse: {
            /** Session Id */
            session_id: string;
            /** Resume Version */
            resume_version: number;
            /** Confirmed */
            confirmed: boolean;
            /** Confirmed At */
            confirmed_at?: string | null;
        };
        /** ResumeEducationPreview */
        ResumeEducationPreview: {
            /**
             * Institution
             * @default
             */
            institution: string;
            /**
             * Degree
             * @default
             */
            degree: string;
            /**
             * Field
             * @default
             */
            field: string;
            /**
             * Dates
             * @default
             */
            dates: string;
            /** Details */
            details?: string[];
            /** Evidence Span Ids */
            evidence_span_ids?: string[];
        };
        /** ResumeEvidencePreview */
        ResumeEvidencePreview: {
            /** Evidence Span Id */
            evidence_span_id: string;
            /** Content */
            content: string;
        };
        /** ResumeExperiencePreview */
        ResumeExperiencePreview: {
            /**
             * Organization
             * @default
             */
            organization: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Dates
             * @default
             */
            dates: string;
            /**
             * Location
             * @default
             */
            location: string;
            /** Responsibilities */
            responsibilities?: string[];
            /** Achievements */
            achievements?: string[];
            /** Technologies */
            technologies?: string[];
            /** Evidence Span Ids */
            evidence_span_ids?: string[];
        };
        /** ResumeLifecycleConflictResponse */
        ResumeLifecycleConflictResponse: {
            /**
             * Detail
             * @enum {string}
             */
            detail: "resume_changed" | "resume_processing" | "resume_error" | "resume_missing" | "resume_unparsed" | "resume_parse_limit";
        };
        /** ResumeParseRequest */
        ResumeParseRequest: {
            /** Generation */
            generation: number;
        };
        /** ResumePreviewResponse */
        ResumePreviewResponse: {
            /** Session Id */
            session_id: string;
            /** Resume Version */
            resume_version: number;
            /** Confirmed */
            confirmed: boolean;
            /** Education */
            education?: components["schemas"]["ResumeEducationPreview"][];
            /** Experience */
            experience?: components["schemas"]["ResumeExperiencePreview"][];
            /** Projects */
            projects?: components["schemas"]["ResumeProjectPreview"][];
            /** Skills */
            skills?: string[];
            /** Resume Quality Issues */
            resume_quality_issues?: string[];
            /** Evidence */
            evidence?: components["schemas"]["ResumeEvidencePreview"][];
        };
        /** ResumeProjectPreview */
        ResumeProjectPreview: {
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Dates
             * @default
             */
            dates: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Actions */
            actions?: string[];
            /** Technologies */
            technologies?: string[];
            /** Outcomes */
            outcomes?: string[];
            /** Evidence Span Ids */
            evidence_span_ids?: string[];
        };
        /** ResumeUploadRejectedResponse */
        ResumeUploadRejectedResponse: {
            /**
             * Detail
             * @enum {string}
             */
            detail: "unsupported_file_type" | "unreadable_file";
        };
        /**
         * ResumeUploadedResponse
         * @description B2 上传确认流：上传即本地提取（零 LLM），等待用户确认解析。
         */
        ResumeUploadedResponse: {
            /** Session Id */
            session_id: string;
            /**
             * Status
             * @default resume_uploaded
             * @constant
             */
            status: "resume_uploaded";
            /** Generation */
            generation: number;
            /** Filename */
            filename: string;
            /** Pages */
            pages: number;
            /** Chars */
            chars: number;
            /** Text Preview */
            text_preview: string;
            /** Parses Used */
            parses_used: number;
            /** Parses Limit */
            parses_limit: number;
            /** Ocr Suggested */
            ocr_suggested: boolean;
        };
        /** ResumeVersionRequiredResponse */
        ResumeVersionRequiredResponse: {
            /**
             * Detail
             * @constant
             */
            detail: "expected_resume_version_required";
        };
        /** RunConversationResponse */
        RunConversationResponse: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
            /** Stage */
            stage?: string | null;
            /** Next Poll Ms */
            next_poll_ms?: number | null;
            /** Messages */
            messages?: components["schemas"]["ConversationMessageResponse"][];
        };
        /** RunExplainResponse */
        RunExplainResponse: {
            /** Run Id */
            run_id: string;
            /** Rank Trace */
            rank_trace?: components["schemas"]["RankTraceResponse"][];
            fusion: components["schemas"]["FusionResponse"];
            /** Stage Durations Ms */
            stage_durations_ms?: {
                [key: string]: number;
            };
            /** Recovery Events */
            recovery_events?: components["schemas"]["RecoveryEventResponse"][];
        };
        /** RunResultResponse */
        RunResultResponse: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
            result: components["schemas"]["ProductResult"];
        };
        /** RunStatusResponse */
        RunStatusResponse: {
            /** Run Id */
            run_id: string;
            /** Session Id */
            session_id: string;
            /** Status */
            status: string;
            /** Stage */
            stage?: string | null;
            /** Result Ready */
            result_ready: boolean;
            /** Warning Codes */
            warning_codes?: string[];
            /** Error Code */
            error_code?: string | null;
            /** Execution Durability */
            execution_durability: string;
            /** Retry After Ms */
            retry_after_ms?: number | null;
            /** Completed Stages */
            completed_stages?: string[];
            /**
             * Total Stages
             * @default 7
             */
            total_stages: number;
            /** Plan Version */
            plan_version: number;
            /** Plan Hash */
            plan_hash?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SessionCreateRequest */
        SessionCreateRequest: Record<string, never>;
        /** SessionResponse */
        SessionResponse: {
            /** Session Id */
            session_id: string;
            /** Status */
            status: string;
        };
        /** SkillGap */
        SkillGap: {
            /** Skill */
            skill: string;
            /**
             * Gap
             * @default
             */
            gap: string;
            /**
             * Priority
             * @default
             * @enum {string}
             */
            priority: "low" | "medium" | "high" | "";
            /** Evidence Span Ids */
            evidence_span_ids?: string[];
        };
        /** StageLatencyResponse */
        StageLatencyResponse: {
            /** Stage */
            stage: string;
            /** P50 Ms */
            p50_ms?: number | null;
            /** P95 Ms */
            p95_ms?: number | null;
        };
        /** SupervisorNote */
        SupervisorNote: {
            /**
             * Kind
             * @constant
             */
            kind: "coach";
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "deepen_entry" | "stagnation" | "finalizable";
            /** Text */
            text: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "pass" | "advise";
            /** Coach Attempt Id */
            coach_attempt_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ValidationErrorItem
         * @description FastAPI/Pydantic 默认校验错误条目的契约镜像（宽容额外键）。
         */
        ValidationErrorItem: {
            /** Loc */
            loc?: (string | number)[];
            /**
             * Msg
             * @default
             */
            msg: string;
            /**
             * Type
             * @default
             */
            type: string;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    capabilities_api_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    request_otp_api_v1_auth_otp_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtpRequestAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_login_otp_api_v1_auth_otp_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    get_profile_api_v1_me_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
        };
    };
    patch_profile_api_v1_me_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfilePatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_sessions_api_v1_me_sessions_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeSessionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SessionCreateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description session quota exhausted */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_resume_api_v1_sessions__session_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_resume_api_v1_sessions__session_id__resume_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeUploadedResponse"];
                };
            };
            /** @description resume file exceeds upload size limit */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeUploadRejectedResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeUploadRejectedResponse"];
                };
            };
        };
    };
    pending_resume_upload_api_v1_sessions__session_id__resume_upload_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeUploadedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_resume_api_v1_sessions__session_id__resume_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeParseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeAcceptedResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeLifecycleConflictResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_preview_api_v1_sessions__session_id__resume_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumePreviewResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeLifecycleConflictResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_confirm_api_v1_sessions__session_id__resume_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ResumeConfirmRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeConfirmResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeLifecycleConflictResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeVersionRequiredResponse"] | components["schemas"]["RequestValidationErrorResponse"];
                };
            };
        };
    };
    get_consultation_api_v1_sessions__session_id__consult_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    continue_consultation_api_v1_sessions__session_id__consult_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsultRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalize_consultation_api_v1_sessions__session_id__consult_finalize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultBriefDraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_match_brief_api_v1_sessions__session_id__match_brief_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchBriefRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchBriefResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_run_api_v1_runs__run_id__execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecuteRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_status_api_v1_runs__run_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_conversation_api_v1_runs__run_id__conversation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunConversationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_result_api_v1_runs__run_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_explain_api_v1_runs__run_id__explain_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunExplainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_run_reaction_api_v1_runs__run_id__reaction_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReactionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    monitoring_overview_api_v1_monitoring_overview_get: {
        parameters: {
            query?: {
                window_hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitoringOverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    monitoring_runs_api_v1_monitoring_runs_get: {
        parameters: {
            query?: {
                window_hours?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecentRunsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
